#!/usr/bin/env python3
"""Generate monition's fork-facing mine-session copy from CMS canonical.

Author-time dev tool (CMS must be present). Single-sources the mine-session
skill and the bundled `method/lesson-routing.md` doc from CMS so they can never
drift by hand — run this after editing the CMS originals, then commit the
generated `src/monition/_generated_cms.py`.

Resolves CMS via $CMS_ROOT, else ~/projects/CMS.

Transform (CMS skill -> fork SKILL_MINE_SESSION body):
  a. remove every `<!-- forkgen:strip -->...<!-- forkgen:/strip -->` block inclusive;
  b. replace each `<!-- forkgen:swap KEY -->` with the body of the matching
     `## swap KEY` section in mine-session.fork-overrides.md;
  c. strip any remaining forkgen `<!-- ... -->` comments; collapse blank lines.
The bundled doc (`method/lesson-routing.md`) is taken verbatim.

Deterministic and idempotent: same CMS inputs -> byte-identical output.
"""
import os
import re
import sys

GENERATED = os.path.join("src", "monition", "_generated_cms.py")

SKILL_REL = os.path.join(".claude", "skills", "mine-session", "SKILL.md")
OVERRIDES_REL = os.path.join(".claude", "skills", "mine-session", "mine-session.fork-overrides.md")
DOC_REL = os.path.join("method", "lesson-routing.md")

_STRIP_RE = re.compile(r"<!-- forkgen:strip -->.*?<!-- forkgen:/strip -->\n?", re.DOTALL)
_SWAP_RE = re.compile(r"<!-- forkgen:swap (\S+) -->")
_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
_SWAP_SECTION_RE = re.compile(r"(?m)^## swap (\S+)[ \t]*$")

_BANNER = (
    "# GENERATED by tools/regen_from_cms.py — do not hand-edit; edit CMS sources and re-run.\n"
    "#\n"
    "# Sources (in CMS):\n"
    "#   .claude/skills/mine-session/SKILL.md\n"
    "#   .claude/skills/mine-session/mine-session.fork-overrides.md\n"
    "#   method/lesson-routing.md\n"
    "#\n"
    "# SKILL_MINE_SESSION    — fork-facing mine-session skill (forkgen-stripped/swapped).\n"
    "# METHOD_LESSON_ROUTING — method/lesson-routing.md, bundled verbatim for forks.\n"
)


def cms_root():
    return os.environ.get("CMS_ROOT") or os.path.expanduser("~/projects/CMS")


def _read(root, rel):
    with open(os.path.join(root, rel), encoding="utf-8") as f:
        return f.read()


def _parse_swaps(overrides_text):
    """`## swap KEY` -> section body (blank-line-trimmed)."""
    parts = _SWAP_SECTION_RE.split(overrides_text)
    swaps = {}
    it = iter(parts[1:])  # drop the pre-heading preamble
    for key, body in zip(it, it):
        swaps[key] = body.strip("\n")
    return swaps


def transform_skill(skill_text, swaps):
    """Apply the forkgen transform (steps a-c) to the CMS skill text."""
    # a. drop CMS-only strip blocks, inclusive of their markers.
    text = _STRIP_RE.sub("", skill_text)

    # b. splice the fork variant in at each swap marker.
    def _swap(m):
        key = m.group(1)
        if key not in swaps:
            raise KeyError(f"no '## swap {key}' section in fork-overrides")
        return swaps[key]
    text = _SWAP_RE.sub(_swap, text)

    # c. drop any remaining forkgen comments (e.g. the authoring note), then
    #    collapse the blank lines they leave behind.
    def _drop_forkgen(m):
        return "" if "forkgen" in m.group(0) else m.group(0)
    text = _HTML_COMMENT_RE.sub(_drop_forkgen, text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.rstrip("\n") + "\n"


def build(root=None):
    """Return {'SKILL_MINE_SESSION': ..., 'METHOD_LESSON_ROUTING': ...} from CMS."""
    root = root or cms_root()
    swaps = _parse_swaps(_read(root, OVERRIDES_REL))
    skill = transform_skill(_read(root, SKILL_REL), swaps)
    doc = _read(root, DOC_REL)
    return {"SKILL_MINE_SESSION": skill, "METHOD_LESSON_ROUTING": doc}


def _emit_literal(name, value):
    if '"""' in value or "\\" in value:
        raise ValueError(f"{name} contains a triple-quote or backslash; extend the emitter")
    if value.startswith('"') or value.endswith('"'):
        raise ValueError(f"{name} starts/ends with a double-quote; extend the emitter")
    return f'{name} = r"""{value}"""\n'


def render(consts):
    return (
        _BANNER
        + "\n"
        + _emit_literal("SKILL_MINE_SESSION", consts["SKILL_MINE_SESSION"])
        + "\n"
        + _emit_literal("METHOD_LESSON_ROUTING", consts["METHOD_LESSON_ROUTING"])
    )


def main():
    root = cms_root()
    if not os.path.isdir(root):
        sys.exit(f"CMS not found at {root} (set $CMS_ROOT). regen is an author tool.")
    out = render(build(root))
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    target = os.path.join(repo_root, GENERATED)
    prev = None
    if os.path.exists(target):
        with open(target, encoding="utf-8") as f:
            prev = f.read()
    with open(target, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"{'unchanged' if prev == out else 'wrote'} {GENERATED} (CMS: {root})")


if __name__ == "__main__":
    main()
